### ISSUE TITLE
Pending tasks before going live

### ISSUE THREAD

**Issue by anandology** [pipalacademy/rajdhani#16]
We'll go live with the challenge by noon today. 

Here are the pending tasks.

## Tasks

- [ ] Task 7: Implement ticket booking flow
- [ ] Task 8: Email conformation on booking
- [ ] Task 9: Login
- [ ] Task 10: My trips page

## Task 7: ticket booking flow

- [ ] add a schema to the table to store the bookings
- [ ] add date to the search form
- [ ] add a new flag `flag_bookings`
- [ ] add a Book button to the train results when `flag_bookings` in on
- [ ] web page with booking form
- [ ] add a placeholder `book_ticket` and `get_trips(email)` functions to db.py

## Task 8: Email confirmation on booking

- [ ] Add sendmail config to config.py
- [ ] Add a `notifications.py` with `send_booking_confirmation_email` function, which the user will have to implement
- [ ] Add `before_request` hook to switch to a test sendmail config. (could this be temporarily implemented in hamr by sending a special HTTP header?)

## Task 9: Login

- [ ] Add a flag `flag_login`
- [ ] Add a login link on the top  nav
- [ ] implement a login page, that just asks for email and logs you in, set that in the cookie
- [ ] show Hello $email and logout links in the nav after successful login

Not sure, what will be the task for users here. 

## Task 10: my trips

- [ ] add a my trips link in the top nav on successful login
- [ ] add `db.get_trips` function
- [ ] implement `/account/trips` endpoint and a trips template
